name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Deno Deployでの認証に必要です。
      contents: read # リポジトリのクローンに必要です。

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # npmを使用していない場合は、`npm ci`を`yarn install`または`pnpm i`に変更してください。
      - name: Install dependencies
        run: npm ci

      # npmを使用していない場合は、`npm run build`を`yarn build`または`pnpm run build`に変更してください。
      - name: Build Astro
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: my-deno-project # TODO： Deno Deployのプロジェクト名に置き換える。
          entrypoint: server/entry.mjs
          root: dist